version: "3.7"
services:
  clients:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /home/clients/app
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    volumes:
      - ./:/home/clients/app
    networks:
      - dev-network
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pgsql:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: clients
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5432:5432
    volumes:
      - /home/lucas/.docker/clients/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge